[package]
name = "pcr"
version = "0.1.0"
edition = "2018"

[dependencies]
gb-io = {git = "https://github.com/dlesl/gb-io"}
bio = "0.25"
rayon = { version = "1.0", optional = true }
log = "0.4"
auto_impl = "0.3.0"

[features]
parallel = ["rayon"]

[dev-dependencies]
assert_approx_eq = "1.1.0"