[package]
name = "pcr"
version = "0.1.0"

[dependencies]
gb-io = { git = "https://github.com/dlesl/gb-io" }
bio = "0.24.0"
itertools = "0.8.0"
rayon = { version = "1.0", optional = true }
log = "0.4"
auto_impl = "0.3.0"

[features]
parallel = ["rayon"]
