[package]
name = "pcr"
version = "0.1.0"

[dependencies]
gb-io = { git = "https://github.com/dlesl/gb-io" }
bio = "0.22"
itertools = "0.7.8"
rayon = { version = "1.0", optional = true }
log = "0.4"

[features]
parallel = ["rayon"]
