[package]
name = "pcr_cli"
version = "0.1.0"

[dependencies]
pcr = { path = "../..", features = ["parallel"] }
gb-io = { git = "https://github.com/dlesl/gb-io" }
clap = "2.32.0"
log = "0.4.5"
env_logger = "0.5"
failure = "0.1.2"